### ISSUE TITLE
Realtime does not exit when connection fails

### ISSUE THREAD

**Issue by jgrund** [whamcloud/realtime#24]
When bringing realtime up in a docker container I see errors like:

```
realtime_1           | { Error: getaddrinfo ENOTFOUND postgres postgres:5432
realtime_1           |     at errnoException (dns.js:50:10)
realtime_1           |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
realtime_1           |   code: 'ENOTFOUND',
realtime_1           |   errno: 'ENOTFOUND',
realtime_1           |   syscall: 'getaddrinfo',
realtime_1           |   hostname: 'postgres',
realtime_1           |   host: 'postgres',
realtime_1           |   port: 5432 }
```

However, the realtime service does not exit but instead keeps running.

After this occurs, the connection does not recover and we need to physically scale down the service to 0 and back up to 1.

When there is any unhandled error in the realtime service, the process should exit.

**Comment by johnsonw** [comment]
Would be interesting to see where the error originates from as we currently have this:
```
pool.on("error", e => {
  console.error("Connection pool encountered an error", e.stack);
  pool.end().then(() => process.exit(1));
});
```

**Comment by jgrund** [comment]
That's the complete trace. 

It's hitting here:

https://github.com/whamcloud/realtime/blob/d6caf9eaddf742a383a1d24d688389504860d53a/index.js#L25-L28

**Comment by jgrund** [comment]
What's interesting about this is it's a sort of deadlock that even `process.exit` does not cause the process to exit.
